### ISSUE TITLE
Fetch User Analytics for Repository Interactions

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-community-insights#8]
#### Objective
Develop a cloud function to fetch user interaction data from our repositories using GraphQL APIs and generate the report.

#### Scope
1. **Data Collection:**
   - Fetch interaction data (forks, pull requests, commits, comments) from repositories using GraphQL APIs.
   - Ensure secure handling of authentication tokens.

2. **Report Generation:**
   - Analyze the fetched data and generate a report ranking users based on their interactions.

**Comment by Mitish98** [comment]
Hi, i can do this task @nomadbitcoin
